//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _220_Mamedov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsTeacher { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
