//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _220_Mamedov
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public int QuestionId { get; set; }
        public int TestId { get; set; }
        public int Answer { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual TestReports TestReports { get; set; }
    }
}
